"""Datos estáticos mínimos de la temporada LPF 2026 para la versión Lite.

El fixture y la foto fija del Apertura provienen de la versión 3.8.70 validada.
Los resultados del Clausura NO se hardcodean: se actualizan desde TyC Sports.
"""
from __future__ import annotations

TOTAL_ROUNDS = 16
APERTURA_ROUNDS = 16
APERTURA_CHAMPION = "Belgrano"
TYC_RESULTS_URL = "https://www.tycsports.com/liga-profesional-de-futbol/fixture-del-clausura-2026-calendario-de-partidos-y-resultados-id750943.html"

CLUB_ALIASES = {'Aldosivi': ['aldosivi'],
 'Argentinos Juniors': ['argentinos', 'argentinos jrs', 'aa argentinos juniors'],
 'Atlético Tucumán': ['atl tucuman', 'atletico tucuman', 'tucuman', 'ca tucuman'],
 'Banfield': ['banfield', 'ca banfield'],
 'Barracas Central': ['barracas', 'barracas central'],
 'Belgrano': ['belgrano', 'ca belgrano'],
 'Boca Juniors': ['boca', 'boca jrs', 'boca juniors', 'ca boca juniors'],
 'Central Córdoba': ['central cordoba', 'central cordoba sde', 'ca central cordoba'],
 'Defensa y Justicia': ['defensa', 'defensa y justicia'],
 'Deportivo Riestra': ['riestra', 'deportivo riestra'],
 'Estudiantes de La Plata': ['estudiantes',
                             'estudiantes lp',
                             'estudiantes de la plata',
                             'edlp',
                             'estudiantes (la plata)'],
 'Estudiantes de Río Cuarto': ['estudiantes rc',
                               'estudiantes de rio cuarto',
                               'estudiantes (rc)',
                               'estudiantes rio cuarto',
                               'estudiantes (río cuarto)',
                               'estudiantes (rio cuarto)'],
 'Gimnasia La Plata': ['gimnasia',
                       'gimnasia lp',
                       'gimnasia y esgrima la plata',
                       'gelp',
                       'gimnasia la plata',
                       'gimnasia (la plata)',
                       'gimnasia y esgrima'],
 'Gimnasia de Mendoza': ['gimnasia m',
                         'gimnasia (m)',
                         'gimnasia y esgrima de mendoza',
                         'gimnasia mendoza',
                         'gimnasia mza',
                         'gimnasia (mza)',
                         'gimnasia (mza )',
                         'gimnasia de mza',
                         'gimnasia y esgrima mendoza'],
 'Godoy Cruz': ['godoy cruz', 'godoy'],
 'Huracán': ['huracan', 'ca huracan'],
 'Independiente': ['independiente', 'ca independiente'],
 'Independiente Rivadavia': ['independiente riv',
                             'independiente rivadavia',
                             'ind rivadavia',
                             'sportivo independiente rivadavia'],
 'Instituto': ['instituto', 'instituto atletico central cordoba'],
 'Lanús': ['lanus', 'ca lanus'],
 "Newell's Old Boys": ['newells', 'newell s old boys', 'newells old boys', 'noob'],
 'Platense': ['platense', 'ca platense'],
 'Racing': ['racing', 'racing club'],
 'River Plate': ['river', 'river plate', 'ca river plate'],
 'Rosario Central': ['central', 'rosario central', 'ca rosario central'],
 'San Lorenzo': ['san lorenzo', 'san lorenzo de almagro'],
 'Sarmiento': ['sarmiento', 'sarmiento junin'],
 'Talleres': ['talleres', 'talleres cordoba'],
 'Tigre': ['tigre', 'ca tigre'],
 'Unión': ['union', 'union santa fe'],
 'Vélez Sarsfield': ['velez', 'velez sarsfield', 'ca velez sarsfield']}

ZONE_A = ['Deportivo Riestra',
 'Boca Juniors',
 'Estudiantes de La Plata',
 'Independiente',
 "Newell's Old Boys",
 'Talleres',
 'Vélez Sarsfield',
 'Instituto',
 'Platense',
 'Unión',
 'Lanús',
 'San Lorenzo',
 'Gimnasia de Mendoza',
 'Central Córdoba',
 'Defensa y Justicia']

ZONE_B = ['River Plate',
 'Barracas Central',
 'Racing',
 'Gimnasia La Plata',
 'Belgrano',
 'Rosario Central',
 'Estudiantes de Río Cuarto',
 'Tigre',
 'Sarmiento',
 'Argentinos Juniors',
 'Huracán',
 'Banfield',
 'Atlético Tucumán',
 'Independiente Rivadavia',
 'Aldosivi']

FIXTURE = [{'f': 1, 'tipo': 'inter', 'zona': None, 'l': 'Defensa y Justicia', 'v': 'Aldosivi'},
 {'f': 1, 'tipo': 'zona', 'zona': 'A', 'l': 'Deportivo Riestra', 'v': 'Boca Juniors'},
 {'f': 1, 'tipo': 'zona', 'zona': 'A', 'l': 'Estudiantes de La Plata', 'v': 'Independiente'},
 {'f': 1, 'tipo': 'zona', 'zona': 'A', 'l': "Newell's Old Boys", 'v': 'Talleres'},
 {'f': 1, 'tipo': 'zona', 'zona': 'A', 'l': 'Vélez Sarsfield', 'v': 'Instituto'},
 {'f': 1, 'tipo': 'zona', 'zona': 'A', 'l': 'Platense', 'v': 'Unión'},
 {'f': 1, 'tipo': 'zona', 'zona': 'A', 'l': 'Lanús', 'v': 'San Lorenzo'},
 {'f': 1, 'tipo': 'zona', 'zona': 'A', 'l': 'Gimnasia de Mendoza', 'v': 'Central Córdoba'},
 {'f': 1, 'tipo': 'zona', 'zona': 'B', 'l': 'River Plate', 'v': 'Barracas Central'},
 {'f': 1, 'tipo': 'zona', 'zona': 'B', 'l': 'Racing', 'v': 'Gimnasia La Plata'},
 {'f': 1, 'tipo': 'zona', 'zona': 'B', 'l': 'Belgrano', 'v': 'Rosario Central'},
 {'f': 1, 'tipo': 'zona', 'zona': 'B', 'l': 'Estudiantes de Río Cuarto', 'v': 'Tigre'},
 {'f': 1, 'tipo': 'zona', 'zona': 'B', 'l': 'Sarmiento', 'v': 'Argentinos Juniors'},
 {'f': 1, 'tipo': 'zona', 'zona': 'B', 'l': 'Huracán', 'v': 'Banfield'},
 {'f': 1, 'tipo': 'zona', 'zona': 'B', 'l': 'Atlético Tucumán', 'v': 'Independiente Rivadavia'},
 {'f': 2, 'tipo': 'inter', 'zona': None, 'l': 'Central Córdoba', 'v': 'Atlético Tucumán'},
 {'f': 2, 'tipo': 'zona', 'zona': 'A', 'l': 'San Lorenzo', 'v': 'Gimnasia de Mendoza'},
 {'f': 2, 'tipo': 'zona', 'zona': 'A', 'l': 'Unión', 'v': 'Lanús'},
 {'f': 2, 'tipo': 'zona', 'zona': 'A', 'l': 'Instituto', 'v': 'Platense'},
 {'f': 2, 'tipo': 'zona', 'zona': 'A', 'l': 'Talleres', 'v': 'Vélez Sarsfield'},
 {'f': 2, 'tipo': 'zona', 'zona': 'A', 'l': 'Independiente', 'v': "Newell's Old Boys"},
 {'f': 2, 'tipo': 'zona', 'zona': 'A', 'l': 'Boca Juniors', 'v': 'Estudiantes de La Plata'},
 {'f': 2, 'tipo': 'zona', 'zona': 'A', 'l': 'Defensa y Justicia', 'v': 'Deportivo Riestra'},
 {'f': 2, 'tipo': 'zona', 'zona': 'B', 'l': 'Independiente Rivadavia', 'v': 'Huracán'},
 {'f': 2, 'tipo': 'zona', 'zona': 'B', 'l': 'Banfield', 'v': 'Sarmiento'},
 {'f': 2, 'tipo': 'zona', 'zona': 'B', 'l': 'Argentinos Juniors', 'v': 'Estudiantes de Río Cuarto'},
 {'f': 2, 'tipo': 'zona', 'zona': 'B', 'l': 'Tigre', 'v': 'Belgrano'},
 {'f': 2, 'tipo': 'zona', 'zona': 'B', 'l': 'Rosario Central', 'v': 'Racing'},
 {'f': 2, 'tipo': 'zona', 'zona': 'B', 'l': 'Gimnasia La Plata', 'v': 'River Plate'},
 {'f': 2, 'tipo': 'zona', 'zona': 'B', 'l': 'Barracas Central', 'v': 'Aldosivi'},
 {'f': 3, 'tipo': 'inter', 'zona': None, 'l': 'Deportivo Riestra', 'v': 'Barracas Central'},
 {'f': 3, 'tipo': 'zona', 'zona': 'A', 'l': 'Estudiantes de La Plata', 'v': 'Defensa y Justicia'},
 {'f': 3, 'tipo': 'zona', 'zona': 'A', 'l': "Newell's Old Boys", 'v': 'Boca Juniors'},
 {'f': 3, 'tipo': 'zona', 'zona': 'A', 'l': 'Vélez Sarsfield', 'v': 'Independiente'},
 {'f': 3, 'tipo': 'zona', 'zona': 'A', 'l': 'Platense', 'v': 'Talleres'},
 {'f': 3, 'tipo': 'zona', 'zona': 'A', 'l': 'Lanús', 'v': 'Instituto'},
 {'f': 3, 'tipo': 'zona', 'zona': 'A', 'l': 'Gimnasia de Mendoza', 'v': 'Unión'},
 {'f': 3, 'tipo': 'zona', 'zona': 'A', 'l': 'Central Córdoba', 'v': 'San Lorenzo'},
 {'f': 3, 'tipo': 'zona', 'zona': 'B', 'l': 'Aldosivi', 'v': 'Gimnasia La Plata'},
 {'f': 3, 'tipo': 'zona', 'zona': 'B', 'l': 'River Plate', 'v': 'Rosario Central'},
 {'f': 3, 'tipo': 'zona', 'zona': 'B', 'l': 'Racing', 'v': 'Tigre'},
 {'f': 3, 'tipo': 'zona', 'zona': 'B', 'l': 'Belgrano', 'v': 'Argentinos Juniors'},
 {'f': 3, 'tipo': 'zona', 'zona': 'B', 'l': 'Estudiantes de Río Cuarto', 'v': 'Banfield'},
 {'f': 3, 'tipo': 'zona', 'zona': 'B', 'l': 'Sarmiento', 'v': 'Independiente Rivadavia'},
 {'f': 3, 'tipo': 'zona', 'zona': 'B', 'l': 'Huracán', 'v': 'Atlético Tucumán'},
 {'f': 4, 'tipo': 'inter', 'zona': None, 'l': 'San Lorenzo', 'v': 'Huracán'},
 {'f': 4, 'tipo': 'zona', 'zona': 'A', 'l': 'Unión', 'v': 'Central Córdoba'},
 {'f': 4, 'tipo': 'zona', 'zona': 'A', 'l': 'Instituto', 'v': 'Gimnasia de Mendoza'},
 {'f': 4, 'tipo': 'zona', 'zona': 'A', 'l': 'Talleres', 'v': 'Lanús'},
 {'f': 4, 'tipo': 'zona', 'zona': 'A', 'l': 'Independiente', 'v': 'Platense'},
 {'f': 4, 'tipo': 'zona', 'zona': 'A', 'l': 'Boca Juniors', 'v': 'Vélez Sarsfield'},
 {'f': 4, 'tipo': 'zona', 'zona': 'A', 'l': 'Defensa y Justicia', 'v': "Newell's Old Boys"},
 {'f': 4, 'tipo': 'zona', 'zona': 'A', 'l': 'Deportivo Riestra', 'v': 'Estudiantes de La Plata'},
 {'f': 4, 'tipo': 'zona', 'zona': 'B', 'l': 'Atlético Tucumán', 'v': 'Sarmiento'},
 {'f': 4, 'tipo': 'zona', 'zona': 'B', 'l': 'Independiente Rivadavia', 'v': 'Estudiantes de Río Cuarto'},
 {'f': 4, 'tipo': 'zona', 'zona': 'B', 'l': 'Banfield', 'v': 'Belgrano'},
 {'f': 4, 'tipo': 'zona', 'zona': 'B', 'l': 'Argentinos Juniors', 'v': 'Racing'},
 {'f': 4, 'tipo': 'zona', 'zona': 'B', 'l': 'Tigre', 'v': 'River Plate'},
 {'f': 4, 'tipo': 'zona', 'zona': 'B', 'l': 'Rosario Central', 'v': 'Aldosivi'},
 {'f': 4, 'tipo': 'zona', 'zona': 'B', 'l': 'Gimnasia La Plata', 'v': 'Barracas Central'},
 {'f': 5, 'tipo': 'inter', 'zona': None, 'l': 'Estudiantes de La Plata', 'v': 'Gimnasia La Plata'},
 {'f': 5, 'tipo': 'zona', 'zona': 'A', 'l': "Newell's Old Boys", 'v': 'Deportivo Riestra'},
 {'f': 5, 'tipo': 'zona', 'zona': 'A', 'l': 'Vélez Sarsfield', 'v': 'Defensa y Justicia'},
 {'f': 5, 'tipo': 'zona', 'zona': 'A', 'l': 'Platense', 'v': 'Boca Juniors'},
 {'f': 5, 'tipo': 'zona', 'zona': 'A', 'l': 'Lanús', 'v': 'Independiente'},
 {'f': 5, 'tipo': 'zona', 'zona': 'A', 'l': 'Gimnasia de Mendoza', 'v': 'Talleres'},
 {'f': 5, 'tipo': 'zona', 'zona': 'A', 'l': 'Central Córdoba', 'v': 'Instituto'},
 {'f': 5, 'tipo': 'zona', 'zona': 'A', 'l': 'San Lorenzo', 'v': 'Unión'},
 {'f': 5, 'tipo': 'zona', 'zona': 'B', 'l': 'Barracas Central', 'v': 'Rosario Central'},
 {'f': 5, 'tipo': 'zona', 'zona': 'B', 'l': 'Aldosivi', 'v': 'Tigre'},
 {'f': 5, 'tipo': 'zona', 'zona': 'B', 'l': 'River Plate', 'v': 'Argentinos Juniors'},
 {'f': 5, 'tipo': 'zona', 'zona': 'B', 'l': 'Racing', 'v': 'Banfield'},
 {'f': 5, 'tipo': 'zona', 'zona': 'B', 'l': 'Belgrano', 'v': 'Independiente Rivadavia'},
 {'f': 5, 'tipo': 'zona', 'zona': 'B', 'l': 'Estudiantes de Río Cuarto', 'v': 'Atlético Tucumán'},
 {'f': 5, 'tipo': 'zona', 'zona': 'B', 'l': 'Sarmiento', 'v': 'Huracán'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'River Plate', 'v': 'Vélez Sarsfield'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Barracas Central', 'v': 'Platense'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Talleres', 'v': 'Rosario Central'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Sarmiento', 'v': 'Estudiantes de La Plata'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Belgrano', 'v': 'Defensa y Justicia'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Lanús', 'v': 'Argentinos Juniors'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Racing', 'v': 'Boca Juniors'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Independiente', 'v': 'Independiente Rivadavia'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Aldosivi', 'v': 'Unión'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Atlético Tucumán', 'v': 'Instituto'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Estudiantes de Río Cuarto', 'v': 'San Lorenzo'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Gimnasia La Plata', 'v': 'Gimnasia de Mendoza'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Tigre', 'v': 'Central Córdoba'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': 'Huracán', 'v': 'Deportivo Riestra'},
 {'f': 6, 'tipo': 'inter', 'zona': None, 'l': "Newell's Old Boys", 'v': 'Banfield'},
 {'f': 7, 'tipo': 'inter', 'zona': None, 'l': 'Unión', 'v': 'Sarmiento'},
 {'f': 7, 'tipo': 'zona', 'zona': 'A', 'l': 'Instituto', 'v': 'San Lorenzo'},
 {'f': 7, 'tipo': 'zona', 'zona': 'A', 'l': 'Talleres', 'v': 'Central Córdoba'},
 {'f': 7, 'tipo': 'zona', 'zona': 'A', 'l': 'Independiente', 'v': 'Gimnasia de Mendoza'},
 {'f': 7, 'tipo': 'zona', 'zona': 'A', 'l': 'Boca Juniors', 'v': 'Lanús'},
 {'f': 7, 'tipo': 'zona', 'zona': 'A', 'l': 'Defensa y Justicia', 'v': 'Platense'},
 {'f': 7, 'tipo': 'zona', 'zona': 'A', 'l': 'Deportivo Riestra', 'v': 'Vélez Sarsfield'},
 {'f': 7, 'tipo': 'zona', 'zona': 'A', 'l': 'Estudiantes de La Plata', 'v': "Newell's Old Boys"},
 {'f': 7, 'tipo': 'zona', 'zona': 'B', 'l': 'Huracán', 'v': 'Estudiantes de Río Cuarto'},
 {'f': 7, 'tipo': 'zona', 'zona': 'B', 'l': 'Atlético Tucumán', 'v': 'Belgrano'},
 {'f': 7, 'tipo': 'zona', 'zona': 'B', 'l': 'Independiente Rivadavia', 'v': 'Racing'},
 {'f': 7, 'tipo': 'zona', 'zona': 'B', 'l': 'Banfield', 'v': 'River Plate'},
 {'f': 7, 'tipo': 'zona', 'zona': 'B', 'l': 'Argentinos Juniors', 'v': 'Aldosivi'},
 {'f': 7, 'tipo': 'zona', 'zona': 'B', 'l': 'Tigre', 'v': 'Barracas Central'},
 {'f': 7, 'tipo': 'zona', 'zona': 'B', 'l': 'Rosario Central', 'v': 'Gimnasia La Plata'},
 {'f': 8, 'tipo': 'inter', 'zona': None, 'l': 'Rosario Central', 'v': "Newell's Old Boys"},
 {'f': 8, 'tipo': 'zona', 'zona': 'A', 'l': 'Vélez Sarsfield', 'v': 'Estudiantes de La Plata'},
 {'f': 8, 'tipo': 'zona', 'zona': 'A', 'l': 'Platense', 'v': 'Deportivo Riestra'},
 {'f': 8, 'tipo': 'zona', 'zona': 'A', 'l': 'Lanús', 'v': 'Defensa y Justicia'},
 {'f': 8, 'tipo': 'zona', 'zona': 'A', 'l': 'Gimnasia de Mendoza', 'v': 'Boca Juniors'},
 {'f': 8, 'tipo': 'zona', 'zona': 'A', 'l': 'Central Córdoba', 'v': 'Independiente'},
 {'f': 8, 'tipo': 'zona', 'zona': 'A', 'l': 'San Lorenzo', 'v': 'Talleres'},
 {'f': 8, 'tipo': 'zona', 'zona': 'A', 'l': 'Unión', 'v': 'Instituto'},
 {'f': 8, 'tipo': 'zona', 'zona': 'B', 'l': 'Gimnasia La Plata', 'v': 'Tigre'},
 {'f': 8, 'tipo': 'zona', 'zona': 'B', 'l': 'Barracas Central', 'v': 'Argentinos Juniors'},
 {'f': 8, 'tipo': 'zona', 'zona': 'B', 'l': 'Aldosivi', 'v': 'Banfield'},
 {'f': 8, 'tipo': 'zona', 'zona': 'B', 'l': 'River Plate', 'v': 'Independiente Rivadavia'},
 {'f': 8, 'tipo': 'zona', 'zona': 'B', 'l': 'Racing', 'v': 'Atlético Tucumán'},
 {'f': 8, 'tipo': 'zona', 'zona': 'B', 'l': 'Belgrano', 'v': 'Huracán'},
 {'f': 8, 'tipo': 'zona', 'zona': 'B', 'l': 'Estudiantes de Río Cuarto', 'v': 'Sarmiento'},
 {'f': 9, 'tipo': 'inter', 'zona': None, 'l': 'Instituto', 'v': 'Estudiantes de Río Cuarto'},
 {'f': 9, 'tipo': 'zona', 'zona': 'A', 'l': 'Talleres', 'v': 'Unión'},
 {'f': 9, 'tipo': 'zona', 'zona': 'A', 'l': 'Independiente', 'v': 'San Lorenzo'},
 {'f': 9, 'tipo': 'zona', 'zona': 'A', 'l': 'Boca Juniors', 'v': 'Central Córdoba'},
 {'f': 9, 'tipo': 'zona', 'zona': 'A', 'l': 'Defensa y Justicia', 'v': 'Gimnasia de Mendoza'},
 {'f': 9, 'tipo': 'zona', 'zona': 'A', 'l': 'Deportivo Riestra', 'v': 'Lanús'},
 {'f': 9, 'tipo': 'zona', 'zona': 'A', 'l': 'Estudiantes de La Plata', 'v': 'Platense'},
 {'f': 9, 'tipo': 'zona', 'zona': 'A', 'l': "Newell's Old Boys", 'v': 'Vélez Sarsfield'},
 {'f': 9, 'tipo': 'zona', 'zona': 'B', 'l': 'Sarmiento', 'v': 'Belgrano'},
 {'f': 9, 'tipo': 'zona', 'zona': 'B', 'l': 'Huracán', 'v': 'Racing'},
 {'f': 9, 'tipo': 'zona', 'zona': 'B', 'l': 'Atlético Tucumán', 'v': 'River Plate'},
 {'f': 9, 'tipo': 'zona', 'zona': 'B', 'l': 'Independiente Rivadavia', 'v': 'Aldosivi'},
 {'f': 9, 'tipo': 'zona', 'zona': 'B', 'l': 'Banfield', 'v': 'Barracas Central'},
 {'f': 9, 'tipo': 'zona', 'zona': 'B', 'l': 'Argentinos Juniors', 'v': 'Gimnasia La Plata'},
 {'f': 9, 'tipo': 'zona', 'zona': 'B', 'l': 'Tigre', 'v': 'Rosario Central'},
 {'f': 10, 'tipo': 'inter', 'zona': None, 'l': 'Vélez Sarsfield', 'v': 'Tigre'},
 {'f': 10, 'tipo': 'zona', 'zona': 'A', 'l': 'Platense', 'v': "Newell's Old Boys"},
 {'f': 10, 'tipo': 'zona', 'zona': 'A', 'l': 'Lanús', 'v': 'Estudiantes de La Plata'},
 {'f': 10, 'tipo': 'zona', 'zona': 'A', 'l': 'Gimnasia de Mendoza', 'v': 'Deportivo Riestra'},
 {'f': 10, 'tipo': 'zona', 'zona': 'A', 'l': 'Central Córdoba', 'v': 'Defensa y Justicia'},
 {'f': 10, 'tipo': 'zona', 'zona': 'A', 'l': 'San Lorenzo', 'v': 'Boca Juniors'},
 {'f': 10, 'tipo': 'zona', 'zona': 'A', 'l': 'Unión', 'v': 'Independiente'},
 {'f': 10, 'tipo': 'zona', 'zona': 'A', 'l': 'Instituto', 'v': 'Talleres'},
 {'f': 10, 'tipo': 'zona', 'zona': 'B', 'l': 'Rosario Central', 'v': 'Argentinos Juniors'},
 {'f': 10, 'tipo': 'zona', 'zona': 'B', 'l': 'Gimnasia La Plata', 'v': 'Banfield'},
 {'f': 10, 'tipo': 'zona', 'zona': 'B', 'l': 'Barracas Central', 'v': 'Independiente Rivadavia'},
 {'f': 10, 'tipo': 'zona', 'zona': 'B', 'l': 'Aldosivi', 'v': 'Atlético Tucumán'},
 {'f': 10, 'tipo': 'zona', 'zona': 'B', 'l': 'River Plate', 'v': 'Huracán'},
 {'f': 10, 'tipo': 'zona', 'zona': 'B', 'l': 'Racing', 'v': 'Sarmiento'},
 {'f': 10, 'tipo': 'zona', 'zona': 'B', 'l': 'Belgrano', 'v': 'Estudiantes de Río Cuarto'},
 {'f': 11, 'tipo': 'inter', 'zona': None, 'l': 'Talleres', 'v': 'Belgrano'},
 {'f': 11, 'tipo': 'zona', 'zona': 'A', 'l': 'Independiente', 'v': 'Instituto'},
 {'f': 11, 'tipo': 'zona', 'zona': 'A', 'l': 'Boca Juniors', 'v': 'Unión'},
 {'f': 11, 'tipo': 'zona', 'zona': 'A', 'l': 'Defensa y Justicia', 'v': 'San Lorenzo'},
 {'f': 11, 'tipo': 'zona', 'zona': 'A', 'l': 'Deportivo Riestra', 'v': 'Central Córdoba'},
 {'f': 11, 'tipo': 'zona', 'zona': 'A', 'l': 'Estudiantes de La Plata', 'v': 'Gimnasia de Mendoza'},
 {'f': 11, 'tipo': 'zona', 'zona': 'A', 'l': "Newell's Old Boys", 'v': 'Lanús'},
 {'f': 11, 'tipo': 'zona', 'zona': 'A', 'l': 'Vélez Sarsfield', 'v': 'Platense'},
 {'f': 11, 'tipo': 'zona', 'zona': 'B', 'l': 'Estudiantes de Río Cuarto', 'v': 'Racing'},
 {'f': 11, 'tipo': 'zona', 'zona': 'B', 'l': 'Sarmiento', 'v': 'River Plate'},
 {'f': 11, 'tipo': 'zona', 'zona': 'B', 'l': 'Huracán', 'v': 'Aldosivi'},
 {'f': 11, 'tipo': 'zona', 'zona': 'B', 'l': 'Atlético Tucumán', 'v': 'Barracas Central'},
 {'f': 11, 'tipo': 'zona', 'zona': 'B', 'l': 'Independiente Rivadavia', 'v': 'Gimnasia La Plata'},
 {'f': 11, 'tipo': 'zona', 'zona': 'B', 'l': 'Banfield', 'v': 'Rosario Central'},
 {'f': 11, 'tipo': 'zona', 'zona': 'B', 'l': 'Argentinos Juniors', 'v': 'Tigre'},
 {'f': 12, 'tipo': 'inter', 'zona': None, 'l': 'Platense', 'v': 'Argentinos Juniors'},
 {'f': 12, 'tipo': 'zona', 'zona': 'A', 'l': 'Lanús', 'v': 'Vélez Sarsfield'},
 {'f': 12, 'tipo': 'zona', 'zona': 'A', 'l': 'Gimnasia de Mendoza', 'v': "Newell's Old Boys"},
 {'f': 12, 'tipo': 'zona', 'zona': 'A', 'l': 'Central Córdoba', 'v': 'Estudiantes de La Plata'},
 {'f': 12, 'tipo': 'zona', 'zona': 'A', 'l': 'San Lorenzo', 'v': 'Deportivo Riestra'},
 {'f': 12, 'tipo': 'zona', 'zona': 'A', 'l': 'Unión', 'v': 'Defensa y Justicia'},
 {'f': 12, 'tipo': 'zona', 'zona': 'A', 'l': 'Instituto', 'v': 'Boca Juniors'},
 {'f': 12, 'tipo': 'zona', 'zona': 'A', 'l': 'Talleres', 'v': 'Independiente'},
 {'f': 12, 'tipo': 'zona', 'zona': 'B', 'l': 'Tigre', 'v': 'Banfield'},
 {'f': 12, 'tipo': 'zona', 'zona': 'B', 'l': 'Rosario Central', 'v': 'Independiente Rivadavia'},
 {'f': 12, 'tipo': 'zona', 'zona': 'B', 'l': 'Gimnasia La Plata', 'v': 'Atlético Tucumán'},
 {'f': 12, 'tipo': 'zona', 'zona': 'B', 'l': 'Barracas Central', 'v': 'Huracán'},
 {'f': 12, 'tipo': 'zona', 'zona': 'B', 'l': 'Aldosivi', 'v': 'Sarmiento'},
 {'f': 12, 'tipo': 'zona', 'zona': 'B', 'l': 'River Plate', 'v': 'Estudiantes de Río Cuarto'},
 {'f': 12, 'tipo': 'zona', 'zona': 'B', 'l': 'Racing', 'v': 'Belgrano'},
 {'f': 13, 'tipo': 'inter', 'zona': None, 'l': 'Racing', 'v': 'Independiente'},
 {'f': 13, 'tipo': 'zona', 'zona': 'A', 'l': 'Boca Juniors', 'v': 'Talleres'},
 {'f': 13, 'tipo': 'zona', 'zona': 'A', 'l': 'Defensa y Justicia', 'v': 'Instituto'},
 {'f': 13, 'tipo': 'zona', 'zona': 'A', 'l': 'Deportivo Riestra', 'v': 'Unión'},
 {'f': 13, 'tipo': 'zona', 'zona': 'A', 'l': 'Estudiantes de La Plata', 'v': 'San Lorenzo'},
 {'f': 13, 'tipo': 'zona', 'zona': 'A', 'l': "Newell's Old Boys", 'v': 'Central Córdoba'},
 {'f': 13, 'tipo': 'zona', 'zona': 'A', 'l': 'Vélez Sarsfield', 'v': 'Gimnasia de Mendoza'},
 {'f': 13, 'tipo': 'zona', 'zona': 'A', 'l': 'Platense', 'v': 'Lanús'},
 {'f': 13, 'tipo': 'zona', 'zona': 'B', 'l': 'Belgrano', 'v': 'River Plate'},
 {'f': 13, 'tipo': 'zona', 'zona': 'B', 'l': 'Estudiantes de Río Cuarto', 'v': 'Aldosivi'},
 {'f': 13, 'tipo': 'zona', 'zona': 'B', 'l': 'Sarmiento', 'v': 'Barracas Central'},
 {'f': 13, 'tipo': 'zona', 'zona': 'B', 'l': 'Huracán', 'v': 'Gimnasia La Plata'},
 {'f': 13, 'tipo': 'zona', 'zona': 'B', 'l': 'Atlético Tucumán', 'v': 'Rosario Central'},
 {'f': 13, 'tipo': 'zona', 'zona': 'B', 'l': 'Independiente Rivadavia', 'v': 'Tigre'},
 {'f': 13, 'tipo': 'zona', 'zona': 'B', 'l': 'Banfield', 'v': 'Argentinos Juniors'},
 {'f': 14, 'tipo': 'inter', 'zona': None, 'l': 'Banfield', 'v': 'Lanús'},
 {'f': 14, 'tipo': 'zona', 'zona': 'A', 'l': 'Gimnasia de Mendoza', 'v': 'Platense'},
 {'f': 14, 'tipo': 'zona', 'zona': 'A', 'l': 'Central Córdoba', 'v': 'Vélez Sarsfield'},
 {'f': 14, 'tipo': 'zona', 'zona': 'A', 'l': 'San Lorenzo', 'v': "Newell's Old Boys"},
 {'f': 14, 'tipo': 'zona', 'zona': 'A', 'l': 'Unión', 'v': 'Estudiantes de La Plata'},
 {'f': 14, 'tipo': 'zona', 'zona': 'A', 'l': 'Instituto', 'v': 'Deportivo Riestra'},
 {'f': 14, 'tipo': 'zona', 'zona': 'A', 'l': 'Talleres', 'v': 'Defensa y Justicia'},
 {'f': 14, 'tipo': 'zona', 'zona': 'A', 'l': 'Independiente', 'v': 'Boca Juniors'},
 {'f': 14, 'tipo': 'zona', 'zona': 'B', 'l': 'Argentinos Juniors', 'v': 'Independiente Rivadavia'},
 {'f': 14, 'tipo': 'zona', 'zona': 'B', 'l': 'Tigre', 'v': 'Atlético Tucumán'},
 {'f': 14, 'tipo': 'zona', 'zona': 'B', 'l': 'Rosario Central', 'v': 'Huracán'},
 {'f': 14, 'tipo': 'zona', 'zona': 'B', 'l': 'Gimnasia La Plata', 'v': 'Sarmiento'},
 {'f': 14, 'tipo': 'zona', 'zona': 'B', 'l': 'Barracas Central', 'v': 'Estudiantes de Río Cuarto'},
 {'f': 14, 'tipo': 'zona', 'zona': 'B', 'l': 'Aldosivi', 'v': 'Belgrano'},
 {'f': 14, 'tipo': 'zona', 'zona': 'B', 'l': 'River Plate', 'v': 'Racing'},
 {'f': 15, 'tipo': 'inter', 'zona': None, 'l': 'Boca Juniors', 'v': 'River Plate'},
 {'f': 15, 'tipo': 'zona', 'zona': 'A', 'l': 'Defensa y Justicia', 'v': 'Independiente'},
 {'f': 15, 'tipo': 'zona', 'zona': 'A', 'l': 'Deportivo Riestra', 'v': 'Talleres'},
 {'f': 15, 'tipo': 'zona', 'zona': 'A', 'l': 'Estudiantes de La Plata', 'v': 'Instituto'},
 {'f': 15, 'tipo': 'zona', 'zona': 'A', 'l': "Newell's Old Boys", 'v': 'Unión'},
 {'f': 15, 'tipo': 'zona', 'zona': 'A', 'l': 'Vélez Sarsfield', 'v': 'San Lorenzo'},
 {'f': 15, 'tipo': 'zona', 'zona': 'A', 'l': 'Platense', 'v': 'Central Córdoba'},
 {'f': 15, 'tipo': 'zona', 'zona': 'A', 'l': 'Lanús', 'v': 'Gimnasia de Mendoza'},
 {'f': 15, 'tipo': 'zona', 'zona': 'B', 'l': 'Racing', 'v': 'Aldosivi'},
 {'f': 15, 'tipo': 'zona', 'zona': 'B', 'l': 'Belgrano', 'v': 'Barracas Central'},
 {'f': 15, 'tipo': 'zona', 'zona': 'B', 'l': 'Estudiantes de Río Cuarto', 'v': 'Gimnasia La Plata'},
 {'f': 15, 'tipo': 'zona', 'zona': 'B', 'l': 'Sarmiento', 'v': 'Rosario Central'},
 {'f': 15, 'tipo': 'zona', 'zona': 'B', 'l': 'Huracán', 'v': 'Tigre'},
 {'f': 15, 'tipo': 'zona', 'zona': 'B', 'l': 'Atlético Tucumán', 'v': 'Argentinos Juniors'},
 {'f': 15, 'tipo': 'zona', 'zona': 'B', 'l': 'Independiente Rivadavia', 'v': 'Banfield'},
 {'f': 16, 'tipo': 'inter', 'zona': None, 'l': 'Gimnasia de Mendoza', 'v': 'Independiente Rivadavia'},
 {'f': 16, 'tipo': 'zona', 'zona': 'A', 'l': 'Central Córdoba', 'v': 'Lanús'},
 {'f': 16, 'tipo': 'zona', 'zona': 'A', 'l': 'San Lorenzo', 'v': 'Platense'},
 {'f': 16, 'tipo': 'zona', 'zona': 'A', 'l': 'Unión', 'v': 'Vélez Sarsfield'},
 {'f': 16, 'tipo': 'zona', 'zona': 'A', 'l': 'Instituto', 'v': "Newell's Old Boys"},
 {'f': 16, 'tipo': 'zona', 'zona': 'A', 'l': 'Talleres', 'v': 'Estudiantes de La Plata'},
 {'f': 16, 'tipo': 'zona', 'zona': 'A', 'l': 'Independiente', 'v': 'Deportivo Riestra'},
 {'f': 16, 'tipo': 'zona', 'zona': 'A', 'l': 'Boca Juniors', 'v': 'Defensa y Justicia'},
 {'f': 16, 'tipo': 'zona', 'zona': 'B', 'l': 'Banfield', 'v': 'Atlético Tucumán'},
 {'f': 16, 'tipo': 'zona', 'zona': 'B', 'l': 'Argentinos Juniors', 'v': 'Huracán'},
 {'f': 16, 'tipo': 'zona', 'zona': 'B', 'l': 'Tigre', 'v': 'Sarmiento'},
 {'f': 16, 'tipo': 'zona', 'zona': 'B', 'l': 'Rosario Central', 'v': 'Estudiantes de Río Cuarto'},
 {'f': 16, 'tipo': 'zona', 'zona': 'B', 'l': 'Gimnasia La Plata', 'v': 'Belgrano'},
 {'f': 16, 'tipo': 'zona', 'zona': 'B', 'l': 'Barracas Central', 'v': 'Racing'},
 {'f': 16, 'tipo': 'zona', 'zona': 'B', 'l': 'Aldosivi', 'v': 'River Plate'}]

OPENING = {'Aldosivi': {'dg': -13, 'ga': 19, 'gf': 6, 'pj': 16, 'pts': 8},
 'Argentinos Juniors': {'dg': 4, 'ga': 13, 'gf': 17, 'pj': 16, 'pts': 29},
 'Atlético Tucumán': {'dg': -5, 'ga': 20, 'gf': 15, 'pj': 16, 'pts': 14},
 'Banfield': {'dg': -2, 'ga': 19, 'gf': 17, 'pj': 16, 'pts': 18},
 'Barracas Central': {'dg': 0, 'ga': 15, 'gf': 15, 'pj': 16, 'pts': 21},
 'Belgrano': {'dg': 4, 'ga': 13, 'gf': 17, 'pj': 16, 'pts': 26},
 'Boca Juniors': {'dg': 13, 'ga': 9, 'gf': 22, 'pj': 16, 'pts': 30},
 'Central Córdoba': {'dg': -10, 'ga': 21, 'gf': 11, 'pj': 16, 'pts': 16},
 'Defensa y Justicia': {'dg': -3, 'ga': 21, 'gf': 18, 'pj': 16, 'pts': 19},
 'Deportivo Riestra': {'dg': -7, 'ga': 12, 'gf': 5, 'pj': 16, 'pts': 11},
 'Estudiantes de La Plata': {'dg': 12, 'ga': 7, 'gf': 19, 'pj': 16, 'pts': 31},
 'Estudiantes de Río Cuarto': {'dg': -19, 'ga': 24, 'gf': 5, 'pj': 16, 'pts': 5},
 'Gimnasia La Plata': {'dg': 0, 'ga': 19, 'gf': 19, 'pj': 16, 'pts': 26},
 'Gimnasia de Mendoza': {'dg': -8, 'ga': 22, 'gf': 14, 'pj': 16, 'pts': 19},
 'Huracán': {'dg': 4, 'ga': 13, 'gf': 17, 'pj': 16, 'pts': 22},
 'Independiente': {'dg': 4, 'ga': 20, 'gf': 24, 'pj': 16, 'pts': 24},
 'Independiente Rivadavia': {'dg': 14, 'ga': 15, 'gf': 29, 'pj': 16, 'pts': 34},
 'Instituto': {'dg': 0, 'ga': 17, 'gf': 17, 'pj': 16, 'pts': 21},
 'Lanús': {'dg': 3, 'ga': 15, 'gf': 18, 'pj': 16, 'pts': 24},
 "Newell's Old Boys": {'dg': -12, 'ga': 27, 'gf': 15, 'pj': 16, 'pts': 15},
 'Platense': {'dg': -5, 'ga': 15, 'gf': 10, 'pj': 16, 'pts': 16},
 'Racing': {'dg': 2, 'ga': 15, 'gf': 17, 'pj': 16, 'pts': 21},
 'River Plate': {'dg': 10, 'ga': 12, 'gf': 22, 'pj': 16, 'pts': 29},
 'Rosario Central': {'dg': 4, 'ga': 16, 'gf': 20, 'pj': 16, 'pts': 28},
 'San Lorenzo': {'dg': 0, 'ga': 14, 'gf': 14, 'pj': 16, 'pts': 22},
 'Sarmiento': {'dg': -7, 'ga': 20, 'gf': 13, 'pj': 16, 'pts': 19},
 'Talleres': {'dg': 4, 'ga': 13, 'gf': 17, 'pj': 16, 'pts': 26},
 'Tigre': {'dg': 3, 'ga': 15, 'gf': 18, 'pj': 16, 'pts': 20},
 'Unión': {'dg': 4, 'ga': 20, 'gf': 24, 'pj': 16, 'pts': 21},
 'Vélez Sarsfield': {'dg': 6, 'ga': 12, 'gf': 18, 'pj': 16, 'pts': 28}}

PREVIOUS_AVERAGES = {'Aldosivi': (33, 32),
 'Argentinos Juniors': (113, 73),
 'Atlético Tucumán': (84, 73),
 'Banfield': (76, 73),
 'Barracas Central': (98, 73),
 'Belgrano': (86, 73),
 'Boca Juniors': (129, 73),
 'Central Córdoba': (84, 73),
 'Defensa y Justicia': (96, 73),
 'Deportivo Riestra': (100, 73),
 'Estudiantes de La Plata': (105, 73),
 'Estudiantes de Río Cuarto': (0, 0),
 'Gimnasia La Plata': (86, 73),
 'Gimnasia de Mendoza': (0, 0),
 'Huracán': (109, 73),
 'Independiente': (110, 73),
 'Independiente Rivadavia': (89, 73),
 'Instituto': (87, 73),
 'Lanús': (109, 73),
 "Newell's Old Boys": (82, 73),
 'Platense': (92, 73),
 'Racing': (123, 73),
 'River Plate': (123, 73),
 'Rosario Central': (113, 73),
 'San Lorenzo': (96, 73),
 'Sarmiento': (70, 73),
 'Talleres': (106, 73),
 'Tigre': (88, 73),
 'Unión': (99, 73),
 'Vélez Sarsfield': (116, 73)}


FALLBACK_RESULTS = [(1, 'Belgrano', 'Rosario Central', 2, 1),
 (1, 'Sarmiento', 'Argentinos Juniors', 2, 3),
 (1, 'Defensa y Justicia', 'Aldosivi', 1, 1),
 (1, 'Gimnasia de Mendoza', 'Central Córdoba', 1, 0),
 (1, 'Racing', 'Gimnasia La Plata', 2, 1),
 (1, 'Vélez Sarsfield', 'Instituto', 1, 0),
 (1, 'Huracán', 'Banfield', 1, 0),
 (1, 'Platense', 'Unión', 2, 2),
 (1, 'Estudiantes de Río Cuarto', 'Tigre', 1, 0),
 (1, "Newell's Old Boys", 'Talleres', 1, 0),
 (1, 'River Plate', 'Barracas Central', 0, 1),
 (1, 'Lanús', 'San Lorenzo', 1, 0),
 (1, 'Atlético Tucumán', 'Independiente Rivadavia', 0, 0),
 (1, 'Estudiantes de La Plata', 'Independiente', 0, 2),
 (1, 'Deportivo Riestra', 'Boca Juniors', 3, 0),
 (2, 'Banfield', 'Sarmiento', 3, 2),
 (2, 'San Lorenzo', 'Gimnasia de Mendoza', 1, 0),
 (2, 'Rosario Central', 'Racing', 0, 0),
 (2, 'Argentinos Juniors', 'Estudiantes de Río Cuarto', 3, 0),
 (2, 'Barracas Central', 'Aldosivi', 1, 0),
 (2, 'Defensa y Justicia', 'Deportivo Riestra', 2, 1),
 (2, 'Gimnasia La Plata', 'River Plate', 1, 0),
 (2, 'Instituto', 'Platense', 2, 1),
 (2, 'Independiente Rivadavia', 'Huracán', 2, 1),
 (2, 'Talleres', 'Vélez Sarsfield', 1, 3),
 (2, 'Independiente', "Newell's Old Boys", 1, 0),
 (2, 'Central Córdoba', 'Atlético Tucumán', 0, 2),
 (3, 'Gimnasia de Mendoza', 'Unión', 2, 0),
 (3, 'Estudiantes de Río Cuarto', 'Banfield', 0, 0),
 (3, 'Belgrano', 'Argentinos Juniors', 0, 1),
 (3, 'Estudiantes de La Plata', 'Defensa y Justicia', 3, 0),
 (3, 'Racing', 'Tigre', 1, 3),
 (3, 'Deportivo Riestra', 'Barracas Central', 0, 1),
 (3, 'Aldosivi', 'Gimnasia La Plata', 1, 2),
 (3, "Newell's Old Boys", 'Boca Juniors', 2, 2),
 (3, 'River Plate', 'Rosario Central', 0, 1),
 (3, 'Lanús', 'Instituto', 0, 1),
 (3, 'Sarmiento', 'Independiente Rivadavia', 2, 1),
 (3, 'Platense', 'Talleres', 0, 4),
 (3, 'Vélez Sarsfield', 'Independiente', 1, 0),
 (3, 'Huracán', 'Atlético Tucumán', 0, 0),
 (3, 'Central Córdoba', 'San Lorenzo', 1, 0),
 (2, 'Boca Juniors', 'Estudiantes de La Plata', 1, 0),
 (2, 'Tigre', 'Belgrano', 0, 0),
 (2, 'Unión', 'Lanús', 2, 1),
 (4, 'Rosario Central', 'Aldosivi', 2, 1),
 (4, 'Independiente Rivadavia', 'Estudiantes de Río Cuarto', 2, 1),
 (4, 'Deportivo Riestra', 'Estudiantes de La Plata', 2, 0),
 (4, 'Atlético Tucumán', 'Sarmiento', 1, 2)]
